### ISSUE TITLE
Using iOS's voice to text will stop transcribing pre-maturely

### ISSUE THREAD

**Issue by Avi0n** [element-hq/element-x-ios#2030] opened 2023-11-05 05:41 UTC
### Steps to reproduce

1. Tap mic icon on iOS keyboard and start talking
2. Transcription will stop pre-maturely 

#### What did you expect?
For the transcription to keep going until I am ready for it to stop.

#### What happened instead?
The transcription ended pre-maturely on it's own.

### Your phone model

iPhone 15 Pro Max

### Operating system version

iOS 17.1

### Application version

1.4.0 (77)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Velin92** [comment] 2023-11-06 10:20
This is actually a known RTE issue, that we also had on legacy El-iOS

**Comment by Avi0n** [comment] 2023-11-24 21:38
This is still an issue for me on two different devices on the latest TestFlight build: 1.4.2 (79)

**Comment by Velin92** [comment] 2023-11-29 16:11
Reopened the issue since we discovered that due to how iOS 17.0 manages input mode this issue is not fixed on the new iOS version.

**Comment by jacotec** [comment] 2024-01-10 10:54
@Velin92 Is there any schedule to fix this? It makes EX more or less unusable in the car, and even in normal use dictation is a pretty helpful functionality.

**Comment by Velin92** [comment] 2024-01-10 14:45
> @Velin92 Is there any schedule to fix this? It makes EX more or less unusable in the car, and even in normal use dictation is a pretty helpful functionality.

We are looking into how to fix this, in the meantime however you can disable the rich text mode in the advanced settings and the dictation should work fine.

**Comment by jacotec** [comment] 2024-01-10 14:51
@Velin92 I already tried this in the past and it did not work, @pixlwave commented in my #2204 that the RTE is always loaded regardless of the switch.

But I'll try again ... maybe something was changed regarding the switch.

**Comment by Velin92** [comment] 2024-01-10 16:28
> @Velin92 I already tried this in the past and it did not work, @pixlwave commented in my #2204 that the RTE is always loaded regardless of the switch.
> 
> But I'll try again ... maybe something was changed regarding the switch.

We recently have changed how the RTE plain text mode is handled, give it a try in the latest version it should at least work when RTE is actually disabled

**Closed** 2024-01-12 16:00 UTC
Labels: T-Defect, S-Minor, O-Frequent, Team: Element X Feature, Z-Schedule, A-Rich-Text-Editor, Z-Labs

**Comment by Avi0n** [comment] 2024-01-16 20:04
@Velin92 On the latest TestFlight build (1.5.2, 85) this issue is solved, but now the app is crashing when pressing the mic again to stop. Opened a new issue to track: https://github.com/element-hq/element-x-ios/issues/2344

**Comment by jacotec** [comment] 2024-01-16 22:24
@Avi0n Good finding - confirmed, it does nor work at all now and immediately crashes on all my devices.

**Comment by stefanceriu** [comment] 2024-01-17 08:20
Thanks for letting us know, we found the problem and we'll fix it asap 👍
