### ISSUE TITLE
Cmd-, should bring up EX settings on macOS, not emulator settings

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2844] opened 2024-05-16 19:59 UTC
### Steps to reproduce

1. Run EX on macOS
2. Want to open settings
3. Hit <kbd>Cmd</kbd><kbd>,</kbd>
4. Ugly annoying iOS emulator config dialog comes up, rather than EX settings

#### What did you expect?

<kbd>Cmd</kbd><kbd>,</kbd> to bring up settings

#### What happened instead?

Brought up the emulator config instead

### Operating system version

macOS 14.4.1

### Application version

600

### Will you send logs?

No

**Comment by Velin92** [comment] 2024-06-03 09:15
dupe of https://github.com/element-hq/element-x-ios/issues/2586

**Closed by Velin92** 2024-06-03 09:15 UTC
Labels: T-Defect
