### ISSUE TITLE
Settings menu disappears

### ISSUE THREAD

**Issue by koehn** [element-hq/element-x-ios#2399] opened 2024-01-28 14:50 UTC
### Steps to reproduce

When I launch Element X, it displays a settings menu between the sidebar icon and the words “All Chats”. 
![IMG_1314](https://github.com/element-hq/element-x-ios/assets/583888/b15179cb-3b06-4de0-b1cb-bac0bf2375b8)

If I leave the app and return, the menu is hidden:

![IMG_1310](https://github.com/element-hq/element-x-ios/assets/583888/a8f9d9ac-122e-483a-97b7-1c17dd301711)

if I force-quit the app, the menu re-appears the next time I launch it, only to disappear if I leave the app and return.

#### What did you expect?
I expect the menu to remain visible.
#### What happened instead?
It disappears. (See screenshots above)

### Your phone model

iPad Air 2022

### Operating system version

iPadOS 17.3

### Application version

Version: 1.5.4 (88)

### Homeserver

https://koehn.com

### Will you send logs?

No

**Comment by pixlwave** [comment] 2024-01-29 10:10
Duplicate of #1918

**Closed by pixlwave** 2024-01-29 10:10 UTC
Labels: T-Defect
