### ISSUE TITLE
Accepting invite on another client doesn’t show up in EX

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2181] opened 2023-11-28 15:21 UTC
### Steps to reproduce

1. Get invited to a room
2. Accept invite on EW
3. Look at EX
4. See unaccepted invite there.

### Application version

445

**Comment by HarHarLinks** [comment] 2024-01-25 17:17
not sure what version 445 is, but i can repro in 1.5.3 (86). Which made me notice that 1.5.4 is available which was not auto-updated. After applying the update, the invite is gone, but it might be due to the update process itself and might not have otherwise.

**Comment by giomfo** [comment] 2024-02-22 18:26
I don't reproduce this issue with v1.5.9(527). I tested with an invite for a group chat and another for a DM.

**Comment by ara4n** [comment] 2024-05-20 16:48
folks are still seeing it (cc @EdGeraghty)

**Comment by ara4n** [comment] 2024-05-20 16:49
![Screenshot 2024-05-20 at 12 48 46](https://github.com/element-hq/element-x-ios/assets/1294269/d255dd23-a78c-41cb-a0a1-64fead501eb2)

(admittedly on android, but i suspect the bug also exists on EXI)

**Comment by manuroe** [comment] 2024-10-01 07:53
Has anyone encountered this issue since we moved to SSS?

**Comment by manuroe** [comment] 2024-11-14 16:38
> Has anyone encountered this issue since we moved to SSS?

Seems not. I am closing the issue.

**Closed by manuroe** 2024-11-14 16:38 UTC
Labels: X-Needs-Rust, T-Defect, S-Major, O-Frequent, A-Invite
