### ISSUE TITLE
Element X not showing up in Sharesheet

### ISSUE THREAD

**Issue by DavyRay** [element-hq/element-x-ios#3373] opened 2024-05-26 02:06 UTC
### Steps to reproduce

When I come to share a photo from my camera roll or an Instagram post, or anything else, I cannot get Element X to show up on the sharesheet.  I swipe across to see the "... more" and go through the list of available apps, but Element X is not one of them.  I had Element before and read that it was broken and that Element X was out... I installed that thinking that the issue would be resolved, but it does not seem to be

### Outcome

Expect app to show up when clicking on Share within an iOS app regardless of app

### Your phone model

iPhone 14 pro

### Operating system version

iOS 17.3

### Application version

Element X v 1.6.8 (107)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by pixlwave** [comment] 2024-10-07 08:38
Closing this as a duplicate of #1477, @jacboy I've asked someone to follow-up on your request however.

**Closed by pixlwave** 2024-10-07 08:38 UTC
Labels: T-Defect
