### ISSUE TITLE
RichTextEditor fails editing message 

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/element-x-ios#1746] opened 2023-09-19 05:42 UTC
The rich text editor fails configuring itself to edit mode and stays empty

STRs:
* send yourself a message the contains both normal text and a code block
* try editing that message
* see the composer not pick up the original text

Example
"""
123

```
123
```
"""

**Comment by manuroe** [comment] 2024-01-19 09:26
@stefanceriu will check it.

**Comment by stefanceriu** [comment] 2024-01-19 10:29
This is still a problem but only when the RTE is in markdown mode

**Comment by giomfo** [comment] 2024-02-23 07:54
@stefanceriu I don't reproduce this issue even by disabling the "Text Formatting" option. What do you mean by "RTE in markdown mode"?

**Comment by stefanceriu** [comment] 2024-02-23 08:26
As in, Settings -> Advanced settings -> Rich text editor: Off


https://github.com/element-hq/element-x-ios/assets/637564/9bfb58b3-5152-4a29-932e-33d783ceefdb

**Comment by Velin92** [comment] 2024-07-16 13:55
seems to be fixed on the latest versione

**Closed by Velin92** 2024-07-16 13:55 UTC
Labels: A-Composer, T-Defect, S-Major, O-Occasional, Team: Element X Feature, A-Rich-Text-Editor
