### ISSUE TITLE
Room name display breaks when leaving and reentering app

### ISSUE THREAD

**Issue by marwing** [element-hq/element-x-ios#2604] opened 2024-03-25 04:05 UTC
### Steps to reproduce

1. Open room
2. notice the room name is displayed flushed left in the room header
3. hide app (go to the home screen or switch app)
4. wait a few seconds
5. switch back to element x
6. notice the room name is now centered in the room header and the name wrapped (when the room name is long enough)

Note: This has the same reproduction steps as #1918 and both involve similar unexpected UI changes, which leads me to believe they may have the same root cause.

#### What did you expect?
![Screenshot 2024-03-25 at 04 53 57](https://github.com/element-hq/element-x-ios/assets/29716248/efc7d772-9838-41c7-89c6-3a7f29f458ca)

#### What happened instead?
![Screenshot 2024-03-25 at 04 54 06](https://github.com/element-hq/element-x-ios/assets/29716248/72b25bab-2f5a-49a4-a46e-654a4d25b2bd)

https://github.com/element-hq/element-x-ios/assets/29716248/3685dd27-ab88-42c0-9b9c-7d237976033b

### Your phone model

iPad Pro (11-inch)

### Operating system version

iPadOS 17.4.1

### Application version

1.6.0 (100)

### Homeserver

Synapse 1.103.0 / Proxy 0.99.15

### Will you send logs?

No

**Comment by pixlwave** [comment] 2024-03-25 10:01
Thanks @marwing. I'm going to close this as a duplicate of #1918, but have linked it so its easy to find those screenshots.

**Closed by pixlwave** 2024-03-25 10:01 UTC
Labels: T-Defect
