### ISSUE TITLE
rotating screen loses draft msg

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2364] opened 2024-01-21 09:53 UTC
### Steps to reproduce

1. Start writing a msg on iphone max
2. Rotate the screen accidentally
3. Lose the draft

#### What did you expect?

don’t lose my drafts!!1!

### Your phone model

iphone 12 pro max

### Operating system version

17.2.1

### Application version

493

### Will you send logs?

No

**Comment by stefanceriu** [comment] 2024-01-21 10:40
Strange, it should've been fixed in https://github.com/element-hq/element-x-ios/pull/2323

**Comment by stefanceriu** [comment] 2024-01-21 11:22
@ara4n the reported app version seems to be wrong, we're at 493 for nightlies and 86 for release 🤔

**Comment by stefanceriu** [comment] 2024-01-21 15:54
I was able to reproduce it but only on a large (max) iPhone. Presumably it has something to do with the split view appearing, recomputing the whole hierarcly and resetting that `hasAlreadyAppeared` `ComposerToolbar` flag

**Comment by stefanceriu** [comment] 2024-01-22 07:01
While we're at it let's also implement some sort of in-memory draft storage solution but do please put it behind a service and a protocol so we can switch to a rust based solution in the future (we need encryption if not in memory)

**Comment by stefanceriu** [comment] 2024-01-22 07:02
[My original question](https://github.com/element-hq/element-x-ios/issues/2275#issuecomment-1877011754) still stands: why does the RTE need to reset its contents on appearance?

**Comment by ara4n** [comment] 2024-01-26 09:57
> @ara4n the reported app version seems to be wrong, we're at 493 for nightlies and 86 for release 🤔

i strongly suspect i misread the 3 as an 8 on the dinky little icon (especially as i filed this in bed with my glasses off, hence accidentally rotating the phone :P)

**Comment by Velin92** [comment] 2024-02-02 16:44
Opening an issue on RTE. I finally discovered what is causing it, but the solution requires to fix an architectural issue on the RTE side.

**Closed** 2024-02-08 17:07 UTC
Labels: A-Composer, T-Defect, S-Major, O-Occasional
