### ISSUE TITLE
Cannot use Element X with an homeserver behind a VPN.

### ISSUE THREAD

**Issue by Railroad6230** [element-hq/element-x-ios#3558] opened 2024-11-26 15:40 UTC
### Steps to reproduce

 0. Enable my VPN tunnel (Wireguard) on iOS
 1. Starting in the "Select your server" view, after selecting "Change account provider"
 2. Setting "Homeserver URL" to the URL of my matrix server, only reachable from within my VPN (tried 'matrix.<mydomain>' and 'https://matrix.<mydomain>')

#### What did you expect?

Element X is able to communicate with my homeserver. 

#### What happened instead?

Element X is unable to communicate with my homeserver:

> [We couldn't reach this homeserver. Please check that you have entered the homeserver URL correctly. If the URL is correct, contact your homeserver administrator for further help.](https://github.com/element-hq/element-x-ios/blob/36980840ed2f23bb3da273472a310c235b9491cf/ElementX/Resources/Localizations/en.lproj/Localizable.strings#L480)

I also don't see any logs on nginx (I'm using nginx as reverse proxy).

Note that Element (not the X) works perfectly fine.

### Your phone model

iPhone 13 Mini

### Operating system version

iOS 18.1.1 (not working either on iOS 17.X and 18.0)

### Application version

Version: 1.9.6 (137) from TestFlight. Also tried with the one available on the App Store.

### Homeserver

Synapse v1.120.0, MSC3861 is used.

### Will you send logs?

Yes

Here are some logs. I've redacted our internal domain name.

[console.2024-11-26-15.log](https://github.com/user-attachments/files/17921992/console.2024-11-26-15.log)

**Comment by pixlwave** [comment] 2024-11-26 18:35
I've just tested this and I'm unable to reproduce it. My test went as follows:
- Install Synapse onto a VM and create an account using `register_new_matrix_user`.
- Adding the VM to Tailscale (wireguard based).
- Enable UFW on the VM so that Synapse isn't available from outside the server.
- Add an iPhone to the same Tailscale.
- Disable WiFi on the iPhone so it definitely unable to reach the VM locally.
- Open Element X and enter the server as `http://vm.tailscale.addess:8008` (I didn't configure a well-known, reverse proxy or any form of TLS).
- Confirm I was able to sign in to the new account through the VPN.

This sounds like a VPN/server-side configuration issue as far as I can tell, so I'm going to close this issue. Feel free to reopen it if you believe this isn't the case and can provide more information to reproduce the problems you're seeing.

**Closed by pixlwave** 2024-11-26 18:35 UTC
Labels: T-Defect
