### ISSUE TITLE
Trying to answer an invite where the inviter has left gives an unhelpful error

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1805] opened 2023-09-26 14:58 UTC
### Steps to reproduce

1. Alice invites Bob to a DM
2. Alice leaves the room
3. Room winks out of existence
4. Bob tries to answer the DM
5. EX says "Error"

#### What did you expect?

Nice error message (or, even better, invite gets cancelled when Alice leaves her side of it)

#### What happened instead?

Ugly error

### Application version

394

### Will you send logs?

Yes

**Comment by stefanceriu** [comment] 2024-05-23 06:58
Dupe of https://github.com/element-hq/element-x-ios/issues/2289

**Closed by stefanceriu** 2024-05-23 06:58 UTC
Labels: T-Defect, S-Major, O-Uncommon, Team: Element X Feature, A-Invite
