### ISSUE TITLE
Having used GitHub to create my matrix.org account makes it impossible to manage the account and connect to Element X

### ISSUE THREAD

**Issue by poliorcetics** [element-hq/element-x-ios#3622] opened 2024-12-14 16:04 UTC
### Steps to reproduce

I wanted to use Element X (iOS) on iPhone with my matrix account.

The issue is, it was created with GitHub and that breaks the whole Matrix product in fun ways

1) Impossible to set a mail
2) Impossible to set a phone number
3) Impossible to change password
4) Impossible to connect to Element X
5) Impossible to generate a QR code
6) Impossible to get version infos about the Element X app since I _have_ to be logged in to access any setting screen.

With just about the worst error messages, that is _none_.

I remember creating a report via "report a problem" at the bottom on the login screen when the app first came out, but it either went nowhere or didn't work since I was never contacted back and it still doesn't work.

#### What did you expect?

I can move from a GitHub created account to a normal one, or barring that, I can use it as I would a regular account, notably connecting to Element X.

#### What happened instead?

Nothing worked. I think I'm basically stuck with existing sessions and that's it.

### Operating system version

iOS 17, latest version

### Application version

I don't know since I can't go past the login screen

### Homeserver

matrix.org

### Will you send logs?

Yes, logs from my Firefox session:

- [issue.txt](https://github.com/user-attachments/files/18136616/issue.txt)
- [log-0.log](https://github.com/user-attachments/files/18136617/log-0.log)

**Comment by Hywan** [comment] 2024-12-14 20:09
cc @pixlwave

**Comment by pixlwave** [comment] 2024-12-16 14:40
@poliorcetics If you'd like to try out Element X right now, you can reset your password using Element Web, at which point you will be able to log into the account with your user ID and the password you just set. There is some documentation for this process here if you need it: https://ems-docs.element.io/books/element-cloud-documentation/page/frequently-asked-questions#bkmrk-how-do-i-add-a-passw

I'm going to close this issue as the root cause is that matrix.org doesn't support yet MAS and the plan is to enable this in February. Once this is done you will be able to sign in using the GitHub connection.

**Closed by pixlwave** 2024-12-16 14:40 UTC
Labels: T-Defect
