### ISSUE TITLE
App freezes for seconds on viewing memberinfo after loading room

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1851] opened 2023-10-02 23:01 UTC
### Steps to reproduce

1. Open a largeish room
2. Immediately tap on the avatar of someone in the timeline
3. Watch a loading spinner for several seconds while the app ux locks entirely solid

#### What did you expect?

responsive app

#### What happened instead?

frozen app for no obvious reason

### Application version

400

### Will you send logs?

No

**Comment by kittykat** [comment] 2023-10-18 09:08
We need a decision from product on what the user options should be (e.g. being able to cancel the action, showing users as and when they're loaded or something else), and from design, we need a design for a solution.

**Comment by giomfo** [comment] 2024-02-23 08:30
This seems a duplicate of https://github.com/element-hq/element-x-android/issues/851

**Comment by manuroe** [comment] 2024-02-23 16:21
yes, this is the iOS facet of the same issue.

**Comment by manuroe** [comment] 2024-03-01 09:53
The app is no more freezing on this screen. The member list display is going to be displayed more quickly soon.

**Closed by manuroe** 2024-03-01 09:53 UTC
Labels: X-Needs-Design, X-Needs-Product, T-Defect, A-Room-Members, S-Major, O-Occasional
