### ISSUE TITLE
Unread filter doesn’t update when you read rooms.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2450] opened 2024-02-09 17:29 UTC
### Steps to reproduce

1. Turn on filters
2. Filter based on unread
3. tap into an unread room and read it
4. go back to the roomlist
5. it still shows the room as unread :(
6. nothing i can do makes it marked as read.

#### What did you expect?

rooms which stay read when you read them

#### What happened instead?

stuck unreads.

### Application version

517

### Will you send logs?

No

**Comment by Velin92** [comment] 2024-02-12 16:44
For me it works fine most of the time, then sometimes the room gets stuck as unread.
The issue is probably not the filter by itself, but the fact that the rooms are stuck as unread.

https://github.com/element-hq/element-x-ios/assets/34335419/3a232679-334d-41d2-8ba9-b3ef731593ad

**Comment by Velin92** [comment] 2024-02-14 11:20
Duplicate of https://github.com/element-hq/element-x-ios/issues/1479

**Closed by Velin92** 2024-02-14 11:20 UTC
Labels: X-Needs-Rust, T-Defect, S-Major, O-Occasional
