### ISSUE TITLE
Historic messages decrypt on cache reloading, but not before

### ISSUE THREAD

**Issue by wrjlewis** [element-hq/element-x-ios#3055] opened 2024-07-17 14:56 UTC
### Steps to reproduce

Sign into a new instance of Element X
Verify your device
Open some chats with historic E2EE message, those messages can appear as UTDs
Clear EX cache in developer settings
All historic messages are now decrypted properly

#### What did you expect?
Historic messages decrypt successfully, and are displayed as such, without having to cache reload.

#### What happened instead?
Historic messages that are shown as UTDs in the timeline seem stuck that way indefinitely. It could be that the keys are being downloaded or processed at the same time as a user trying to open the message, EX is unable to show the message and presents it as a UTD, and subsequently doesn't attempt to decrypt the message again in future. 

### Your phone model

iPhone 12 pro

### Operating system version

MacOS and iOS

### Application version

1.6.13

### Homeserver

Synapse 

### Will you send logs?

No

**Comment by wrjlewis** [comment] 2024-07-17 15:59
> This sounds like it might be similar to #3045 but viewed from a different perspective.

Yup sounds similar - ie EX caching the fact it's not immediately been able to decrypt the event

**Comment by ara4n** [comment] 2024-07-23 10:21
Getting similar on EXA too: https://github.com/element-hq/element-x-android-rageshakes/issues/2418

**Comment by richvdh** [comment] 2024-07-26 11:25
Since this seems common to EXI and EXA, and likely a problem in the rust layer, I have pulled out a common issue to track fixing this in the rust layer: https://github.com/matrix-org/matrix-rust-sdk/issues/3768

**Comment by wrjlewis** [comment] 2024-08-19 08:18
Still seeing this, as are others I know running EX, consistently. 
@neilisfragile  ran into this on Friday on switchover to SSS which forces a logout / login.

**Comment by richvdh** [comment] 2024-08-19 10:08
Please do send rageshakes for any observed UTDs. Our decisions for which UTD causes get fixed are pretty directly based on the number of rageshakes we see for those causes.

**Comment by neilisfragile** [comment] 2024-08-19 10:39
Here is a rageshake, though I (and I think anyone) can consistently reproduce. 
https://github.com/element-hq/element-x-ios-rageshakes/issues/2088

**Comment by ara4n** [comment] 2024-09-02 20:36
i wonder if this is the same as https://github.com/element-hq/element-x-ios/issues/2417.

It might also be happening on EXA in https://github.com/element-hq/element-x-android/issues/3382

**Comment by pixlwave** [comment] 2024-09-09 10:09
I saw the same thing on migrating my personal account to SSS and logged in/out multiple times wondering if cross-signing was broken. A force quit worked for me rather than clearing the cache.

**Comment by pixlwave** [comment] 2024-09-10 08:11
Ok nice, #3215 includes an SDK update with that PR.

**Comment by manuroe** [comment] 2024-09-11 07:53
@pixlwave can you verify it is fixed in the EXI app?

**Closed** 2024-09-11 09:27 UTC
Labels: T-Defect, A-E2EE, S-Major, O-Occasional, X-Release-Blocker

**Comment by richvdh** [comment] 2024-12-18 09:55
Per https://github.com/matrix-org/matrix-rust-sdk/issues/3768#issuecomment-2550863993: fixed in EXI 1.8.0
