### ISSUE TITLE
Can't continue from network that can't reach matrix.org

### ISSUE THREAD

**Issue by tearfulDalvik** [element-hq/element-x-ios#3296] opened 2024-09-18 04:54 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
Very start, at the onboarding screen.

2. What do you click?
- Connect to a network that can't reach matrix.org, but can reach my homeserver
- Hit continue

#### What did you expect?
Allow me to enter my homeserver address and sign in

#### What happened instead?
The loading bar hangs
 ![IMG_0023](https://github.com/user-attachments/assets/fc463f83-2131-4193-931b-0e557094a28f)

### Your phone model

iPhone 15 Pro

### Operating system version

iOS 17

### Homeserver

Synapse 1.115.0

### Will you send logs?

Yes

**Comment by pixlwave** [comment] 2024-09-18 09:00
Duplicate of https://github.com/element-hq/element-x-ios/issues/3028

**Closed by pixlwave** 2024-09-18 09:00 UTC
Labels: T-Defect
