### ISSUE TITLE
Room latest visible events have regressed and repeatedly get stuck.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2645] opened 2024-04-03 16:44 UTC
### Steps to reproduce

1. Look at your room list
2. Observe that roughly once a page, a room shows a stale preview.
3. Open the room
4. Go back to room list.
5. See that the stale preview is (typically) still shown.

For instance, SRE Team Lobby is very clearly the odd one out here (showing a spurious old cached preview, rather than an accurate preview)

![image](https://github.com/element-hq/element-x-ios/assets/1294269/ba759afc-f8bd-4acd-9079-18d662194937)

#### What did you expect?

Reliable room previews.

#### What happened instead?

Regressed unreliable room previews, roughly around the time that the event cache code started to land.

### Application version

563

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by stefanceriu** [comment] 2024-06-25 12:13
I can't reproduce it myself for what it's worth. I'll keep an eye on it though.

**Comment by ara4n** [comment] 2024-06-27 13:37
Current working theory here is that if the most recent event in a room is invisible, then we'll show the last visible event (which could be horribly stale).  Eventually the visible_rooms list may update, pulling in the last 20 events for the visible rooms, which might be enough to pull in a visible event, and so 'fix' the behaviour.

The correct behaviour is for the SDK to spider rooms for visible events in order to get an accurate preview (and accurately calculate unread and notification state clientside, and also index for FTS in future).

I'm worried that the client-side list ordering (i.e. Simplified Sliding Sync) implementation on rust-sdk might be unaware of this failure mode, and may not be fixing it (or may make it even worse, given it presumably removes the visible_rooms list).

**Comment by manuroe** [comment] 2024-07-09 12:47
https://github.com/element-hq/element-x-ios/pull/3014 replaces the old logic of visible rooms and should improve the situation. Please rageshake if you meet the problem again

**Comment by manuroe** [comment] 2024-07-11 09:16
We discussed it with the team. We are confident it is fixed now.

**Closed by manuroe** 2024-07-11 09:16 UTC
Labels: X-Needs-Rust, A-Timeline, T-Defect, S-Major, O-Uncommon
