### ISSUE TITLE
Message fails to send in new DM

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-x-ios#1093] opened 2023-06-16 14:10 UTC
### Steps to reproduce

1. Click the button bottom-right to "Start chat"
2. On the "Start chat" screen, search for a user and click on them
3. Type a message and send it right away
4. See red exclamation mark next to the message
5. Navigate away and then back to the DM
6. Don't see a message
7. Try to send another message and see red exclamation mark next to it again

**It doesn't look like the DM is actually crated**

For the purposes of testing, I was trying to create a DM with `@agelessant:matrix.org`

#### What did you expect?
Message is queued and sent, I see the local echo right away

#### What happened instead?
Message was not sent, don't know why

### Your phone model

iPhone 11

### Application version

1.1.5 (241)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by alfogrillo** [comment] 2023-06-19 10:54
@kittykat this may be related with a [caching issues](https://github.com/matrix-org/matrix-rust-sdk/issues/2078) we have on the rust sdk.

Can you check if "clearing the cache" works (available just on EX nightly)?
Cleaning the cache tends to fix membership change issues on the rust sdk.

Eg: if you leave a direct room (or the other person does) you may need to clear the cache to see the correct behavior.

Please let me know if this makes any difference.

![d](https://github.com/vector-im/element-x-ios/assets/19324622/807bca2c-498b-4b44-a73d-13260c981e3a)

**Comment by Johennes** [comment] 2023-06-19 11:37
@ashughes1 could you take over for @kittykat here while she is out?

**Comment by ashughes1** [comment] 2023-06-19 11:43
> @ashughes1 could you take over for @kittykat here while she is out?

Sure, I will try to take a look today.

**Comment by ashughes1** [comment] 2023-06-20 10:35
I was able to reproduce this before clearing cache, but now that I have cleared cache I cannot reproduce it.

**Comment by Johennes** [comment] 2023-06-20 11:18
Thanks for re-testing. Considering this an instance of https://github.com/matrix-org/matrix-rust-sdk/issues/2078 for now then.

**Comment by Johennes** [comment] 2023-06-20 11:18
Duplicate of https://github.com/matrix-org/matrix-rust-sdk/issues/2078

**Closed as not planned by Johennes** 2023-06-20 11:18 UTC
Labels: A-Send event, T-Defect, S-Major, O-Uncommon, A-DMs
