### ISSUE TITLE
Invites don’t local echo

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#3177] opened 2024-08-17 21:47 UTC
### Steps to reproduce

1. Invite a user to a room
2. Sit looking at the membership list
3. Nothing seems to happen
4. Go out of the list after 30s or so
5. Go back in
6. *Now* you see the invited user as “pending”

This is a subset of https://github.com/element-hq/element-x-ios/issues/2090

#### What did you expect?

reliable invites

#### What happened instead?

lack of local echo makes them feel super flakey. or perhaps the membership list isn’t updating despite remote echo?

### Application version

683

### Will you send logs?

No

**Comment by pixlwave** [comment] 2024-08-19 07:39
Duplicate of #1189.

**Closed by pixlwave** 2024-08-19 07:39 UTC
Labels: T-Defect, X-Maybe-Release-Blocker
