### ISSUE TITLE
App icon badge remains after all messages are read in Element-x-iOS

### ISSUE THREAD

**Issue by m4h4** [element-hq/element-x-ios#3527] opened 2024-11-18 13:07 UTC
### Steps to reproduce

I am experiencing an issue where the app icon badge on my iOS device continues to display a "1" even after all messages in the Element app have been read and the badge should disappear. This occurs consistently across multiple conversations and devices.

1. Open the Element app on an iOS device.
2. Receive a new message.
3. Read the message.
4. Observe that the app icon badge still shows a "1".
5. Try closing and reopening the app.
6. The badge persists.
![IMG_4555](https://github.com/user-attachments/assets/7d049395-bdce-4485-b052-4e1a546b6728)

#### What did you expect?

The app icon badge should disappear once all messages in a conversation have been read.

#### What happened instead?

The app icon badge persisted.

### Your phone model

iPhone 15 Pro

### Operating system version

18.1

### Application version

1.9.5 (136)

### Homeserver

fairydust.space

### Will you send logs?

No

**Comment by pixlwave** [comment] 2024-11-18 13:24
Duplicate of #3151.

**Closed by pixlwave** 2024-11-18 13:24 UTC
Labels: T-Defect

**Comment by m4h4** [comment] 2024-11-19 00:16
I'm not sure that this is the same bug. #3151 is about an unreliable count, but in this bug the badge always shows the right count +1.
