### ISSUE TITLE
User avatar disappear after re-opening the app

### ISSUE THREAD

**Issue by Guanran928** [element-hq/element-x-ios#2523] opened 2024-03-04 19:57 UTC
### Steps to reproduce

1. Start Element X iOS
2. Scroll down for a little bit 
3. Quit the app & wait for a few seconds 
4. Re-open the app, see user’s avatar and new chat button has disappeared

![IMG_0056](https://github.com/element-hq/element-x-ios/assets/68757440/ccb8234c-1e50-4b35-b5c3-27bb17493f99)

### Your phone model

iPad Pro

### Application version

TestFlight 1.5.10 (94)

### Will you send logs?

No

**Comment by pixlwave** [comment] 2024-03-05 09:19
Duplicate of #1918.

**Closed as completed by pixlwave** 2024-03-05 09:19 UTC
Labels: T-Defect
