### ISSUE TITLE
Sending a message when offline may silently lose the message

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1726] opened 2023-09-17 09:37 UTC
### Steps to reproduce

1. Sent a message
2. Spotted that the app said “offline”
3. Went to room list
4. Went back
5. Message entirely lost forever

#### What did you expect?

App should *never* lose msgs

#### What happened instead?

Bad queueing; lost msg.

https://github.com/vector-im/element-x-ios-rageshakes/issues/888

### Application version

385

### Will you send logs?

Yes

**Comment by jplatte** [comment] 2023-10-25 14:20
Is this still reproducible (I think it shouldn't be)?

**Comment by kittykat** [comment] 2023-11-23 13:34
@jplatte 100% reproducible for me:

1. Switch on airplane mode
2. Go to my test room (created as a room, converted to DM, I am only member)
3. Send (2) message(s) - I was intending to test sequence
4. Switch off airplane mode
5. Watch both messages vanish

**Comment by jplatte** [comment] 2023-11-23 13:37
When you say the messages *vanished*, do you mean no messages are displayed at all anymore? If yes, a rageshake would be helpful.

**Comment by kittykat** [comment] 2023-11-23 13:46
@jplatte The two messages I tried to send from iOS went from being displayed as failed messages while I was in airplane mode to no longer being shown in the timeline at all once I switched off airplane mode. All other historical messages are still shown in the timeline. I can do a screen recording if that would be helpful?

**Comment by jplatte** [comment] 2023-11-23 13:49
No, I don't think a screencast helps. Have you checked that the failed messages haven't "just" moved higher up though?

**Comment by kittykat** [comment] 2023-11-23 13:51
@jplatte they move higher on Android, but on iOS, I cannot see them higher up

**Comment by jplatte** [comment] 2023-11-23 13:54
That's even more confusing 🥲

I'll look at the rageshake soon.

**Comment by manuroe** [comment] 2024-01-08 14:41
EIX 1.5.2 nightly is also better for handling network retries when network is back. It also keeps the messages and moves it into sent failure after the timeout. So, I cannot reproduce anymore the bug in the scenario described at https://github.com/element-hq/element-x-ios/issues/1726#issuecomment-1824449242.
However, moving back to the room list and reenter the room can lose the failed sent messages but it is not 100% reproductible. I do not know if it is a SDK or app only issue. Android seems not impacted by this problem.

**Comment by ara4n** [comment] 2024-01-10 14:51
i just reproduced the 100% vanish bug. The app wasn't showing as offline and i was on 3 bars of 5G:
 * Sent two messages
 * They didn't send, for whatever reason - hollow circle
 * Wait 20s or so
 * Get bored and switch room
 * Switch back again: messges entirely gone. They had *not* jumped upwards 20 msgs.

Have rageshaked.

**Comment by ara4n** [comment] 2024-01-10 15:23
> they move higher on Android, but on iOS, I cannot see them higher up

to be clear, on iOS there is *also* the related-but-not-the-same bug that unsent messages can end up 'stuck' 20 msgs higher in the timeline: https://github.com/element-hq/element-x-ios/issues/1279

**Comment by Velin92** [comment] 2024-01-10 15:32
Does Android actually store the timeline/room instance even after the room is dismissed? @bmarty 
Because iOS deallocated a room in the exact moment it is dismissed, which means that on the Rust side the queue for that room is actually also probably deallocated.
@timokoesters how does this bit work? https://github.com/matrix-org/matrix-rust-sdk/blob/9fd52e5df76f376519a0d27f727acc90144518d6/crates/matrix-sdk-ui/src/timeline/mod.rs#L295-L301
Does the timeline store the message immediately on the actual disk storage as soon as it gets put in the queue?

**Comment by timokoesters** [comment] 2024-01-29 13:04
I tried to reproduce it with this patch, but it looks fine on Android. If someone wants to reproduce it on iOS, try this:

```diff
diff --git a/crates/matrix-sdk/src/room/futures.rs b/crates/matrix-sdk/src/room/futures.rs
index ebe2b6f05..8c2297c1f 100644
--- a/crates/matrix-sdk/src/room/futures.rs
+++ b/crates/matrix-sdk/src/room/futures.rs
@@ -36,7 +36,7 @@ use tracing::{debug, Instrument, Span};

 use super::Room;
 use crate::{
-    attachment::AttachmentConfig, utils::IntoRawMessageLikeEventContent, Result,
+    attachment::AttachmentConfig, utils::IntoRawMessageLikeEventContent, Error, Result,
     TransmissionProgress,
 };
 #[cfg(feature = "image-proc")]
@@ -200,8 +200,9 @@ impl<'a> IntoFuture for SendRawMessageLikeEvent<'a> {
                 content,
             );

-            let response = room.client.send(request, None).await?;
-            Ok(response)
+            Err(Error::NoOlmMachine) // Trigger an error
         };

         Box::pin(fut.instrument(tracing_span))

```

**Comment by Velin92** [comment] 2024-01-29 18:00
I investigate the issue a bit and this seems to be caused by the fact that we call the `unsubscribe` function from `RoomListItem` every time the room is removed from the navigation, which I mean makes total sense. 
But as soon as we resubscribe to the room, and the timeline is generated again, but is removing all the unsent items.
Just to test this I tried with @timokoesters 's patch, sent a bunch of failed messages, and everytime I was unsubscribing to a room, and resubscribing to it, the timeline was regenerated.
As soon as I stopped calling the `unsubscribe` function the messages were kept... however this is not ideal ofc.
From what I understand Android is also calling this function when exiting a room, so I really don't get why the issue is present only on iOS.
Maybe tomorrow we can't try to check this together @timokoesters

**Comment by Velin92** [comment] 2024-02-21 15:32
@manuroe @timokoesters 
Btw opened this issue on the rust sdk repo:
https://github.com/matrix-org/matrix-rust-sdk/issues/3152

This should fix the issue on iOS, and also fix the issue on both platfortms that happens when we have unsent messages in the room, but we scroll down in the room list, removing the room from the SS window, which when re-entering deletes the unsent messages

**Comment by stefanceriu** [comment] 2024-06-18 06:17
I believe this has been fixed with introduction of the new message sending queue. Please reopen if you see it again.

**Closed by stefanceriu** 2024-06-18 06:17 UTC
Labels: X-Needs-Rust, A-Timeline, T-Defect, S-Critical, O-Occasional, A-Offline
