### ISSUE TITLE
Green invite dot lies

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2818] opened 2024-05-08 14:01 UTC
### Steps to reproduce

1. Get invited to a room
2. Accept on another client
3. Green dot remains on EXI

#### What did you expect?

Green dot should stop lying. In fact, shouldn't it be going away entirely?

### Application version

593

### Will you send logs?

No

**Comment by stefanceriu** [comment] 2024-05-08 14:32
Dupe of https://github.com/element-hq/element-x-ios/issues/2395, but while you're here please submit a rageshake, I updated the logs a while back to try to see what's happening https://github.com/element-hq/element-x-ios/commit/546a9d81858ed166811fd318060ef7b3cdb9d209

Otherwise, yes, it's all going away asap.

**Closed by stefanceriu** 2024-05-08 14:32 UTC
Labels: T-Defect
