### ISSUE TITLE
Unread messages are displayed where no unread messages are there

### ISSUE THREAD

**Issue by ich777** [element-hq/element-x-ios#2461] opened 2024-02-13 08:02 UTC
### Steps to reproduce

Don't know if that is easily reproducible, I just installed Element X in favor to Element, logged in to my account and now Element X displays that I have 12 unread messages as in the screenshot (both on the same account):
![24-02-07 15-59-43 4140](https://github.com/element-hq/element-x-ios/assets/28066518/1201c598-3934-4961-a89c-44a573e0875b)

### Outcome

Only display unread messages.

I'm not 100% sure if I'm here in the right spot to report this because I sometimes notice on the "old" Element app that when somebody texts me that I have 13 messages unread, after I open up the message, read it and close Element the banner with 13 disappears.
Maybe it's a server issue but is there some way to clean out those old messages? On the desktop app (Windows/Linux) I don't see that behavior.

I'm happy to send logs if needed.

### Your phone model

iPhone 15

### Operating system version

17.3.1

### Application version

1.5.5 (89)

### Homeserver

matrix.minenet.at | Synapse 1.100.0

### Will you send logs?

Yes

**Comment by sefidel** [comment] 2024-02-14 08:07
Duplicate of #2066?

**Comment by ich777** [comment] 2024-02-14 08:37
Not quite sure since I have no unread notifications whatsoever.

On the "old" Element App the badge doesn't show up at all, if someone sends me a text the badge becomes 13, when I go into the App, read the message and close it the badge disappears.

On the Element-X App the badge always show 12 messages, if someone sends me a text the badge becomes 13, when I go into the App, read the message and close it the badge shows 12 messages.

I'm not sure what the issue is over here, I have no unread messages anywhere, it also seems like that I'm the only user that is affected from this behavior on my server.

**Comment by sefidel** [comment] 2024-02-14 09:23
Sounds like exactly that issue for me. I also have 27 'stuck' notifications.

**Comment by Velin92** [comment] 2024-02-14 10:40
Duplicate of https://github.com/element-hq/element-x-ios/issues/2066

**Closed by Velin92** 2024-02-14 10:40 UTC
Labels: T-Defect
